Calculate used power based on how many bees are in the mApiary
GTNewHorizons/KubaTech pull request #87
Opened 2023-07-12 17:32 UTC by minecraft7771

- Instead of max slots, it will calculate the consumed power based on bees
- Replaced the calculation of using 99% of an an amp with the array that consumes the recipe amps. (e.g. 1 bee will consume 30.720 EU/t

2023-07-12 17:44 UTC, BlueWeabo approved these changes
IMO. This is a good change as tiers of this machine should be smart enough to not use extra power for slots, which aren't used in them. Its like asking a MCR to always consume x256 more power just because it has a max of 256 parallels and you are doing only 1.

2023-07-12 20:11 UTC, Dream-Master approved these changes

2023-07-12 20:41 UTC, kuba6000 requested changes
I nerfed it to match the EIG behaviour. The idea is that you pay energy for the bigger environment/space for your bees/crops. But if the rest of the team wants it to work more like GT machines then please also do that to EIG.

2023-07-12 20:43 UTC, minecraft7771 commented
I asked in meta-dev yesterday and the people that did respond were in favor of changing it to match GT machines. After all you could just use smaller energy hatches to get the same behavior but its more tedious. We expect something smarter from UV+ multis. Blue also suggested that I put it into both, but I wasn't sure if this would mess with the OC mechanic that the EIG has for vanilla crops.

2023-07-12 20:47 UTC, kuba6000 commented
> I asked in meta-dev yesterday and the people that did respond were in favor of changing it to match GT machines. After all you could just use smaller energy hatches to get the same behavior but its more tedious. We expect something smarter from UV+ multis. Blue also suggested that I put it into both, but I wasn't sure if this would mess with the OC mechanic that the EIG has for vanilla crops.

Oh I totally forgot about that OC mechanic in EIG

2023-07-12 20:49 UTC, kuba6000 requested changes

2023-07-12 20:49 UTC, kuba6000 commented on src/main/java/kubatech/tileentity/gregtech/multiblock/GT_MetaTileEntity_MegaIndustrialApiary.java
> +                    this.lEUt = -GT_Values.VP[6] * workingBees;
No need for additional variable.
```suggestion
                    this.lEUt = -GT_Values.VP[6] * mStorage.size();
```

2023-07-12 21:09 UTC, kuba6000 commented
> I asked in meta-dev yesterday and the people that did respond were in favor of changing it to match GT machines. After all you could just use smaller energy hatches to get the same behavior but its more tedious. We expect something smarter from UV+ multis. Blue also suggested that I put it into both, but I wasn't sure if this would mess with the OC mechanic that the EIG has for vanilla crops.

What about the `t` variable (https://gtnh.miraheze.org/wiki/Bees#Comb_calculation)? It is dependant on voltage, it is buffing output from the bees so also an OC mechanic. And also one of the reasons I nerfed the energy consumption. (I didn't replied anything on meta-dev bacause I forgot about it)
All introduced in this pr: https://github.com/GTNewHorizons/KubaTech/pull/43

2023-07-12 21:20 UTC, minecraft7771 commented
I see I was not told before hand. Would it then make sense to draw atleast the provided voltage instead of flat out LuV? Then the PR would pratically reduce amperage reduction as much as it could. So 1 bee on for example 16A ZPM would still draw ZPM but only 1A. What would you think about this proposal?

2023-07-15 09:18 UTC, kuba6000 commented
> I see I was not told before hand. Would it then make sense to draw atleast the provided voltage instead of flat out LuV? Then the PR would pratically reduce amperage reduction as much as it could. So 1 bee on for example 16A ZPM would still draw ZPM but only 1A. What would you think about this proposal?

I don't think that would change much, if you are talking about multiple hatches. Just use one hatch, that will draw 2 amps. Also `t` variable is currently calculated based on EU/t and is floating point number (1x ZPM hatch -> 7.5 t, 2x ZPM hatch -> 8.0 t, 3x ZPM hatch -> 8.292481 t). I think there is no changes needed, EIG works the same from the start and no one complained about it?

2023-07-15 19:11 UTC, minecraft7771 commented
I'll close it for now.

2023-07-15 19:11 UTC, closed without merging